services:
  - type: web
    name: nastools
    env: docker
    plan: standard
    autoDeploy: false
    disk:
      name: data
      mountPath: /nas-tools
      sizeGB: 10
    envVars:
      - key: PORT
        value: 7681